# Generated by Django 5.0.4 on 2024-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoaichat_video_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='chat',
        ),
        migrations.AddField(
            model_name='video',
            name='messages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VideoAIChat',
        ),
    ]
