# Generated by Django 5.0.4 on 2024-07-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_chat_video_messages_delete_videoaichat'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
